#
# Automagically generated by Approximatrix Simply Fortran 3.19
#
FC="gfortran"
CC="gcc"
AR="ar"
WRC="windres"
PRJTK="sfprjtk"
RM=rm -f

# To determine path to system libraries on macOS >= 10.15
SDKPATH=`xcrun --show-sdk-path`

IDIR=-I"/Applications/Simply Fortran.app/Contents/Resources/gcc/include/" 

LDIR=-L"/Applications/Simply Fortran.app/Contents/Resources/gcc/lib/" 


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS= -ffree-line-length-256 -ffixed-line-length-256

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -J/Users/rainerreichel/Documents/Quadtree/modules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS) -I$(SDKPATH)/usr/include

"build/feaps1.o": "feaps1.for"
	@echo Compiling feaps1.for
	@$(FC) -c -o "build/feaps1.o" $(FFLAGS) "feaps1.for"

"build/feaps2.o": "feaps2.for"
	@echo Compiling feaps2.for
	@$(FC) -c -o "build/feaps2.o" $(FFLAGS) "feaps2.for"

"build/feaps3.o": "feaps3.for"
	@echo Compiling feaps3.for
	@$(FC) -c -o "build/feaps3.o" $(FFLAGS) "feaps3.for"

"build/feaps4.o": "feaps4.for" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_data.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.mod" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.mod"
	@echo Compiling feaps4.for
	@$(FC) -c -o "build/feaps4.o" $(FFLAGS) "feaps4.for"

"build/feaps5.o": "feaps5.for"
	@echo Compiling feaps5.for
	@$(FC) -c -o "build/feaps5.o" $(FFLAGS) "feaps5.for"

"build/feaps6.o": "feaps6.for"
	@echo Compiling feaps6.for
	@$(FC) -c -o "build/feaps6.o" $(FFLAGS) "feaps6.for"

"/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o": "Geom_Module.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/vector_module.mod"
	@echo Compiling Geom_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" $(FFLAGS) "Geom_Module.f90"
"/Users/rainerreichel/Documents/Quadtree/modules/segment_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" : "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" .EXISTSONLY
	@echo Compiling Geom_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" $(FFLAGS) "Geom_Module.f90"

"/Users/rainerreichel/Documents/Quadtree/build/main.o": "main.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.mod"
	@echo Compiling main.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/main.o" $(FFLAGS) "main.f90"

"/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o": "Point_Module.f90"
	@echo Compiling Point_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" $(FFLAGS) "Point_Module.f90"
"/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/seed_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/intrsc_point_module.mod" : "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" .EXISTSONLY
	@echo Compiling Point_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" $(FFLAGS) "Point_Module.f90"

"/Users/rainerreichel/Documents/Quadtree/build/Qtree.o": "Qtree.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/seed_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/segment_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_data.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.mod"
	@echo Compiling Qtree.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Qtree.o" $(FFLAGS) "Qtree.f90"

"/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o": "Qtree_module.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/seed_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/intrsc_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/segment_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.mod"
	@echo Compiling Qtree_module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" $(FFLAGS) "Qtree_module.f90"
"/Users/rainerreichel/Documents/Quadtree/modules/qtree_data.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.mod" : "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" .EXISTSONLY
	@echo Compiling Qtree_module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" $(FFLAGS) "Qtree_module.f90"

"/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o": "SortSearch_module.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod"
	@echo Compiling SortSearch_module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" $(FFLAGS) "SortSearch_module.f90"
"/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.mod" : "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" .EXISTSONLY
	@echo Compiling SortSearch_module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" $(FFLAGS) "SortSearch_module.f90"

"/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o": "Vector_Module.f90" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod"
	@echo Compiling Vector_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" $(FFLAGS) "Vector_Module.f90"
"/Users/rainerreichel/Documents/Quadtree/modules/vector_module.mod" : "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" .EXISTSONLY
	@echo Compiling Vector_Module.f90
	@$(FC) -c -o "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" $(FFLAGS) "Vector_Module.f90"

clean: .SYMBOLIC
	@echo Deleting build/feaps1.o and related files
	@$(RM) "build/feaps1.o"
	@echo Deleting build/feaps2.o and related files
	@$(RM) "build/feaps2.o"
	@echo Deleting build/feaps3.o and related files
	@$(RM) "build/feaps3.o"
	@echo Deleting build/feaps4.o and related files
	@$(RM) "build/feaps4.o"
	@echo Deleting build/feaps5.o and related files
	@$(RM) "build/feaps5.o"
	@echo Deleting build/feaps6.o and related files
	@$(RM) "build/feaps6.o"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" "/Users/rainerreichel/Documents/Quadtree/modules/segment_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/segment_module.smod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/polygon_module.smod"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/main.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/main.o"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/Point_Module.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/point_module.smod" "/Users/rainerreichel/Documents/Quadtree/modules/seed_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/seed_point_module.smod" "/Users/rainerreichel/Documents/Quadtree/modules/intrsc_point_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/intrsc_point_module.smod"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/Qtree.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/Qtree.o"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_data.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_data.smod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_input.smod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/qtree_module.smod"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" "/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/sortsearch_module.smod"
	@echo Deleting /Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o and related files
	@$(RM) "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" "/Users/rainerreichel/Documents/Quadtree/modules/vector_module.mod" "/Users/rainerreichel/Documents/Quadtree/modules/vector_module.smod"
	@echo Deleting Quadtree
	@$(RM) "Quadtree"

"Quadtree":  "build/feaps1.o" "build/feaps2.o" "build/feaps3.o" "build/feaps4.o" "build/feaps5.o" "build/feaps6.o" "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" "/Users/rainerreichel/Documents/Quadtree/build/main.o" "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" "/Users/rainerreichel/Documents/Quadtree/build/Qtree.o" "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" "build/Quadtree.prj.target"
	@echo Generating Quadtree
	@$(FC) -o "Quadtree" -static-libgfortran -static-libgcc -static-libstdc++ -Wl,-syslibroot,$(SDKPATH) "build/feaps1.o" "build/feaps2.o" "build/feaps3.o" "build/feaps4.o" "build/feaps5.o" "build/feaps6.o" "/Users/rainerreichel/Documents/Quadtree/build/Geom_Module.o" "/Users/rainerreichel/Documents/Quadtree/build/main.o" "/Users/rainerreichel/Documents/Quadtree/build/Point_Module.o" "/Users/rainerreichel/Documents/Quadtree/build/Qtree.o" "/Users/rainerreichel/Documents/Quadtree/build/Qtree_module.o" "/Users/rainerreichel/Documents/Quadtree/build/SortSearch_module.o" "/Users/rainerreichel/Documents/Quadtree/build/Vector_Module.o" $(LDIR) $(PRJ_LFLAGS)

all: "Quadtree" .SYMBOLIC

